services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: northwind-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
      - ./init:/init

volumes:
  sqldata:
